- { path: '/mood/sliders', method: get, action: 'Mood.sliders' }
- { path: '/', method: get, action: 'Mood.sliders' }
- { path: '/set/sliders', method: post, action: 'Mood.set_sliders' }
- { path: '/get/sliders', method: get, action: 'Mood.get_sliders' }
- { path: '/hunger/dec', method: get, action: 'Mood.decrement_hunger_slider' }